version: '3.0'
services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - '443:443'
    restart: always
    volumes:
      - data_wp:/var/www/html/
    networks:
      - inception
  mariadb:
    build: ./requirements/mariadb/
    env_file:
      - .env
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - data_db:/var/lib/mysql
    networks:
      - inception
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress/
    env_file:
      - .env
    ports:
      - '9000:9000'
    volumes:
      - data_wp:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
volumes:
  data_wp:
  data_db:
networks:
  inception:
   driver: bridge